(***********************************************************************)
(*                                                                     *)
(*                           Objective Caml                            *)
(*                                                                     *)
(*            Xavier Leroy, projet Cristal, INRIA Rocquencourt         *)
(*                                                                     *)
(*  Copyright 1996 Institut National de Recherche en Informatique et   *)
(*  en Automatique.  All rights reserved.  This file is distributed    *)
(*  under the terms of the Q Public License version 1.0.               *)
(*                                                                     *)
(***********************************************************************)

(* $Id: clflags.ml,v 1.49 2005/08/01 15:51:09 xleroy Exp $ *)

(* Command-line parameters *)

let objfiles = ref ([] : string list)   (* .cmo and .cma files *)
and ccobjs = ref ([] : string list)     (* .o, .a, .so and -cclib -lxxx *)
and dllibs = ref ([] : string list)     (* .so and -dllib -lxxx *)

let compile_only = ref false            (* -c *)
and output_name = ref (None : string option) (* -o *)
and include_dirs = ref ([] : string list)(* -I *)
and no_std_include = ref false          (* -nostdlib *)
and print_types = ref false             (* -i *)
and make_archive = ref false            (* -a *)
and debug = ref false                   (* -g *)
and fast = ref false                    (* -unsafe *)
and link_everything = ref false         (* -linkall *)
and custom_runtime = ref false          (* -custom *)
and output_c_object = ref false         (* -output-obj *)
and ccopts = ref ([] : string list)     (* -ccopt *)
and classic = ref false                 (* -nolabels *)
and nopervasives = ref false            (* -nopervasives *)
and preprocessor = ref(None : string option) (* -pp *)
let save_types = ref false              (* -stypes *)
and use_threads = ref false             (* -thread *)
and use_vmthreads = ref false           (* -vmthread *)
and noassert = ref false                (* -noassert *)
and verbose = ref false                 (* -verbose *)
and noprompt = ref false                (* -noprompt *)
and init_file = ref (None : string option)   (* -init *)
and use_prims = ref ""                  (* -use-prims ... *)
and use_runtime = ref ""                (* -use-runtime ... *)
and principal = ref false               (* -principal *)
and recursive_types = ref false         (* -rectypes *)
and make_runtime = ref false            (* -make_runtime *)
and gprofile = ref false                (* -p *)
and c_compiler = ref Config.bytecomp_c_compiler (* -cc *)
and c_linker = ref Config.bytecomp_c_linker (* -cc *)
and no_auto_link = ref false            (* -noautolink *)
and dllpaths = ref ([] : string list)   (* -dllpath *)
and make_package = ref false            (* -pack *)
and for_package = ref (None: string option) (* -for-pack *)
let dump_parsetree = ref false          (* -dparsetree *)
and dump_rawlambda = ref false          (* -drawlambda *)
and dump_lambda = ref false             (* -dlambda *)

and dump_instr = ref false              (* -dinstr *)
and minsol = ref false                 (* -minsol *)
and dump_constraints = ref false        (* -dconstr *)
and dump_ref_constraints = ref false    (* -drconstr *)
and dump_ref_vars = ref false           (* -drvars *)
and print_subs = ref false              (* -dsubs *)
and dump_qexprs = ref false             (* -dqexprs *)
and dump_qualifs = ref false            (* -dqualifs *)
and dump_queries = ref false            (* -dqueries *)
and dump_frames = ref false             (* -dframes *)
and raw_frames = ref false              (* -draw *)
and dump_graph = ref false              (* -dgraph *)
and log_queries = ref false             (* -lqueries *)
and check_queries = ref false            (* -cqueries *)
and brief_quals = ref false              (* -bquals *)
and esimple = ref false                 (* -esimple *)
and no_simple = ref false               (* -no-simple *)
and verify_simple = ref false           (* -verify-simple *)
and less_qualifs = ref false            (* -lqualifs *)
and no_anormal = ref false            (* -anormal *)
and use_list = ref false                (* -wlist *)
and kill_simplify = ref false           (* -ksimpl *)
and always_use_backup_prover = ref false (* -defprover *)
and use_qprover = ref false             (* -qprover *)
and qpdump = ref false                  (* -qpdump *)
and cache_queries = ref false           (* -cqueries *)
and psimple = ref true                  (* -psimple *)
and no_simple_subs = ref false          (* -no-simple-subs *)
and builtins_file = ref None              (* -use_builtins *)
and simpguard = ref false                (* simplify guard *)
and no_recrefs = ref false              (* true out recursive refinements *)
and no_recvarrefs = ref false           (* no top-level refinements on recvars *)
and ck_mlq = ref false                  (* do a quick incomplete check over the mlq constraints *)
and summarize = ref None                (* dump a summary of program to disk and terminate *)
and dsmeasures = ref false              (* don't strip measure names *)

and verbose = ref false                 (* -verb *)
let keep_asm_file = ref false           (* -S *)
let optimize_for_speed = ref true       (* -compact *)

and dump_cmm = ref false                (* -dcmm *)
let dump_selection = ref false          (* -dsel *)
let dump_live = ref false               (* -dlive *)
let dump_spill = ref false              (* -dspill *)
let dump_split = ref false              (* -dsplit *)
let dump_scheduling = ref false         (* -dscheduling *)
let dump_interf = ref false             (* -dinterf *)
let dump_prefer = ref false             (* -dprefer *)
let dump_regalloc = ref false           (* -dalloc *)
let dump_reload = ref false             (* -dreload *)
let dump_scheduling = ref false         (* -dscheduling *)
let dump_linear = ref false             (* -dlinear *)
let keep_startup_file = ref false       (* -dstartup *)
let dump_combine = ref false            (* -dcombine *)

let native_code = ref false             (* set to true under ocamlopt *)
let inline_threshold = ref 10

let dont_write_files = ref false        (* set to true under ocamldoc *)

let std_include_flag prefix =
  if !no_std_include then ""
  else (prefix ^ (Filename.quote Config.standard_library))
;;

let std_include_dir () =
  if !no_std_include then [] else [Config.standard_library]
;;
