#!/bin/sh

OCAML=./liquid.run
QUALFLAGS="-no-anormal -dqualifs -lqualifs"
FILE=$1

rm -f $FILE.quals $FILE.annot
$OCAML $QUALFLAGS $FILE 1> /dev/null 2> $FILE.quals
$OCAML -dframes $FILE
BASE=`basename $FILE .ml`
DIR=`dirname $FILE`
cat /tmp/liq.annot | ./fix-annot.py $FILE > $DIR/$BASE.annot
