#!/bin/bash
#not actually a regression test
OCAML=./ocaml.run
FLAGS="-dqexprs -dframes"
QUALFLAGS="-dqualifs -lqualifs"
POSFILE=postests
NEGFILE=negtests

if [[ $1 == "" ]]
then
  TMPDIR=/tmp
else
  TMPDIR=$1
fi

rm -f $TMPDIR/*.lilog

FILE=$POSFILE" "$NEGFILE

echo Generating qualifiers where needed...

for i in `cat $FILE`
do
  cat $i.quals 1> /dev/null 2> /dev/null
  if [[ $? != 0 ]]
  then
    ./ocaml $QUALFLAGS < $i 1> /dev/null 2> $i.quals
  fi
done

echo done.

echo RUNNING POSFILE
for i in `cat $POSFILE`
do
  echo RUNNING: $i 
  LOGFILE=$TMPDIR"/"${i/\//_}".lilog"
  time $OCAML $FLAGS $i &> $LOGFILE
  if [ $? = 0 ] 
  then 
    echo "SUCCESS!"
  else
    echo "FAILURE :("
  fi
  grep "TOTAL" $LOGFILE | tail -n1
done
echo DONE

echo RUNNING NEGFILE
for i in `cat $NEGFILE`
do
  echo RUNNING: $i 
  time $OCAML $FLAGS $i &> $TMPDIR"/"${i/\//_}".lilog"
  if [ $? = 1 ] 
  then 
    echo "SUCCESS!"
  else
    echo "FAILURE :("
  fi
  grep "TOTAL" $LOGFILE | tail -n1
done
echo DONE

FILE=$POSFILE"\n"$NEGFILE
FILE=${FILE/\//_}

#OUT_FILES=`ls $TMPDIR"/*.lilog"`


#grovel through output files for stats below:

#IN=0
#for i in $OUT_FILES
#do
#   $IN 

#done
