#!/bin/bash

TMPDIR=/tmp

OUT_FILES=`ls $TMPDIR"/"*.lilog`

#grovel through output files for stats below:

echo "Timing: "
for i in $OUT_FILES
do
   s=`grep -n "\#\#time\#\#" $i | tail -n1 -` 
   d=`grep -n "\#\#endtime\#\#" $i | tail -n1 -`
   s=`expr "$s" : '\([0-9]*\)'`
   d=`expr "$d" : '\([0-9]*\)'`
   let "s = $d - $s"
   f=`head -n$d $i | tail -n$s -`
   tot=`expr "$
done
