#!/bin/bash
#not actually a regression test
OCAML=./liquid.run
FLAGS="-dframes -cacheq -v 9"
QUALFLAGS="-no-anormal -dqualifs -lqualifs"
POSFILE=postests
NEGFILE=negtests
#HANDQUALS_ONLY="yep"

if [[ $1 == "" ]]
then
  export TMPDIR=/tmp
else
  export TMPDIR=$1
fi

rm -f $TMPDIR/*.lilog*
#rm -f DML/*.quals
#rm -f DMLex/*.quals
#rm -f examples-liquid/*.quals

echo Generating qualifiers where needed...

if [[ $HANDQUALS_ONLY ]]
then
  echo "User specified hand quals only"
else
  for i in `cat $POSFILE $NEGFILE`
  do
#    cat $i.quals 1> /dev/null 2> /dev/null
#    if [[ $? != 0 ]]
#    then
    rm -f $i.quals
    $OCAML $QUALFLAGS $i 1> /dev/null 2> $i.quals
#    fi
  done
fi
echo done.

echo RUNNING $POSFILE TESTS
for i in `cat $POSFILE`
do
  echo -n "(" > $TMPDIR/sum
  for j in $(seq 0 2)
  do
    command time -f '%e' -o $TMPDIR/tm $OCAML -v 0 $FLAGS $i 2>&1 > /dev/null
    t=`cat $TMPDIR/tm | tr -d '\n'`
    echo -n "$t + " >> $TMPDIR/sum
  done
  echo -n "0" >> $TMPDIR/sum
  echo ") / 3" >> $TMPDIR/sum
  avg=`cat /dev/null | bc $TMPDIR/sum`
  echo "$i: $avg"
done
echo DONE

exit 0
